CREATE TABLE IF NOT EXISTS linux (
  id MEDIUMINT NOT NULL AUTO_INCREMENT,
  node VARCHAR(255),
  user VARCHAR(255),
  pool VARCHAR(255),
  start DATETIME,
  end DATETIME,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS windows (
  id MEDIUMINT NOT NULL AUTO_INCREMENT,
  node VARCHAR(255),
  user VARCHAR(255),
  pool VARCHAR(255),
  start DATETIME,
  end DATETIME,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS status (
  id MEDIUMINT NOT NULL AUTO_INCREMENT,
  node VARCHAR(255),
  status VARCHAR(255),
  pool VARCHAR(255),
  start DATETIME,
  end DATETIME,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS exception (
  id MEDIUMINT NOT NULL AUTO_INCREMENT,
  user VARCHAR(255),
  start DATETIME,
  end DATETIME,
  wall_time INT,
  PRIMARY KEY (id)
);
